######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 11:12:16 2018
######################################################################

TEMPLATE = app
TARGET = Write2File
INCLUDEPATH += .

# Input
SOURCES += write2file.cpp
