######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 18:34:13 2018
######################################################################

TEMPLATE = app
TARGET = AnotherMenu
INCLUDEPATH += .

# Input
HEADERS += anothermenu.h
SOURCES += anothermenu.cpp main.cpp

QT += widgets
