######################################################################
# Automatically generated by qmake (3.0) Sun Sep 23 16:18:03 2018
######################################################################

TEMPLATE = app
TARGET = loadjson
INCLUDEPATH += .

# Input
SOURCES += loadjsonobj.cpp

#add C++11 support
CONFIG += c++11

QT -= gui
