######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 10:45:16 2018
######################################################################

TEMPLATE = app
TARGET = FileSize
INCLUDEPATH += .

# Input
SOURCES += filesize.cpp
