######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 11:02:04 2018
######################################################################

TEMPLATE = app
TARGET = ReadFile
INCLUDEPATH += .

# Input
SOURCES += readfile.cpp
