######################################################################
# Automatically generated by qmake (3.0) Fri Jul 6 15:30:33 2018
######################################################################

TEMPLATE = app
TARGET = Escaping
INCLUDEPATH += .

# Input
SOURCES += 13-escaping_characters.cpp
