######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 15:19:27 2018
######################################################################

TEMPLATE = app
TARGET = PushButton
INCLUDEPATH += .

# Input
SOURCES += pushbutton.cpp

QT += widgets
