######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 12:32:47 2018
######################################################################

TEMPLATE = app
TARGET = FilePath
INCLUDEPATH += .

# Input
SOURCES += file_path.cpp
