######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 11:26:05 2018
######################################################################

TEMPLATE = app
TARGET = CopyingFiles
INCLUDEPATH += .

# Input
SOURCES += copying_files.cpp
