######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 14:59:30 2018
######################################################################

TEMPLATE = app
TARGET = Cursors
INCLUDEPATH += .

# Input
SOURCES += cursors.cpp

QT += widgets
