######################################################################
# Automatically generated by qmake (3.0) Sat Jul 7 22:44:34 2018
######################################################################

TEMPLATE = app
TARGET = QDateTime
INCLUDEPATH += .

#add C++11 support
CONFIG += c++11

# Input
SOURCES += 13-qdatetime_class.cpp

#Remove GUI support
QT -= gui
