######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 17:24:43 2018
######################################################################

TEMPLATE = app
TARGET = SimpleMenu
INCLUDEPATH += .

# Input
HEADERS += simplemenu.h
SOURCES += main.cpp simplemenu.cpp

QT += widgets
