######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 14:05:29 2018
######################################################################

TEMPLATE = app
TARGET = Tooltip
INCLUDEPATH += .

# Input
SOURCES += tooltip.cpp

QT += widgets
