######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 12:19:01 2018
######################################################################

TEMPLATE = app
TARGET = SpecialPaths
INCLUDEPATH += .

# Input
SOURCES += special_paths.cpp
