######################################################################
# Automatically generated by qmake (3.0) Wed Sep 19 18:08:57 2018
######################################################################

TEMPLATE = app
TARGET = Click
INCLUDEPATH += .

# Input
HEADERS += click.h
SOURCES += main.cpp click.cpp

QT += widgets
