######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 15:50:59 2018
######################################################################

TEMPLATE = app
TARGET = PlusMinus
INCLUDEPATH += .

# Input
HEADERS += plusminus.h
SOURCES += main.cpp plusminus.cpp

QT += widgets
