######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 12:07:03 2018
######################################################################

TEMPLATE = app
TARGET = DirsIntro
INCLUDEPATH += .

# Input
SOURCES += dirs_intro.cpp
