######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 11:51:34 2018
######################################################################

TEMPLATE = app
TARGET = FileTimes
INCLUDEPATH += .

# Input
SOURCES += last_read_n_modified.cpp
