######################################################################
# Automatically generated by qmake (3.0) Sun Sep 23 17:08:05 2018
######################################################################

TEMPLATE = app
TARGET = loadjsonarray
INCLUDEPATH += .

# Input
SOURCES += loadjsonarray.cpp

QT -= gui
