######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 13:48:42 2018
######################################################################

TEMPLATE = app
TARGET = Simple
INCLUDEPATH += .

# Input
SOURCES += simple.cpp

QT += widgets
