######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 02:10:31 2018
######################################################################

TEMPLATE = app
TARGET = QMap
INCLUDEPATH += .

# Input
SOURCES += 5-qmap.cpp
