######################################################################
# Automatically generated by qmake (3.0) Fri Jul 6 15:14:41 2018
######################################################################

TEMPLATE = app
TARGET = SampleWindow
INCLUDEPATH += .

# Input
SOURCES += sampleWindow.cpp

QT += widgets
