######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 11:39:26 2018
######################################################################

TEMPLATE = app
TARGET = Owner
INCLUDEPATH += .

# Input
SOURCES += file_owner_n_group.cpp
