######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 13:06:31 2018
######################################################################

TEMPLATE = app
TARGET = ListDir
INCLUDEPATH += .

# Input
SOURCES += listing_dir.cpp
