######################################################################
# Automatically generated by qmake (3.0) Sun Jul 8 14:37:25 2018
######################################################################

TEMPLATE = app
TARGET = AppIcon
INCLUDEPATH += .

# Input
SOURCES += appIcon.cpp

QT += widgets
