######################################################################
# Automatically generated by qmake (3.0) Sun Sep 23 17:58:09 2018
######################################################################

TEMPLATE = app
TARGET = loadmixedjsondata
INCLUDEPATH += .

# Input
SOURCES += loadmixedjsondata.cpp

QT -= gui
